name = "Sherlock"
uuid = "50c525cd-8faa-4dfa-b5e0-1fbe0ebc7ed3"
authors = ["Casey Kneale"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
